# Generated by Django 4.1.7 on 2023-03-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Rutina',
        ),
    ]
